name: Maven verify (no Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Start MongoDB service (wait for readiness)
        run: |
          # wait for MongoDB service to be ready on localhost:27017
          for i in {1..30}; do
            (echo > /dev/tcp/localhost/27017) >/dev/null 2>&1 && break || sleep 1
          done

      - name: Build and run tests (skip docker-specific tests)
        env:
          # point tests to the service started by this job
          TEST_MONGO_URI: 'mongodb://localhost:27017/kaiburrdb'
        run: |
          mvn -B -U -DskipTests=false -Dspring.profiles.active=ci verify
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ping:1})'" --health-interval=10s --health-timeout=5s --health-retries=5
